### ISSUE TITLE
Filter is not working correctly

### ISSUE THREAD

**Issue by 2lx** [yegappan/bufselect#2]
Steps to reproduce:
1. open the buffer selection menu, enter a filter.
2. open any buffer/close the menu.
3. open the buffer selection menu again, filter does not work until I press 'backspace'.

This change will fix it:
```
diff --git a/autoload/bufselect.vim b/autoload/bufselect.vim
index 06af62c..bb21ca4 100644
--- a/autoload/bufselect.vim
+++ b/autoload/bufselect.vim
@@ -31,6 +31,7 @@ let s:popup_winid = -1
 
 " Edit the buffer selected from the popup menu
 func s:editBuffer(id, result) abort
+  let s:filter_text = ''
   if a:result <= 0
     return
   endif
```

**Comment by yegappan** [comment]
Thanks for reporting the issue. I have fixed this problem in the 13c77c6 commit.
